spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003172
  
server:
  port: 8090
  
logging:
  path: /opt/logs/100003172
  file: ${logging.path}/apollo-adminservice.log
